spring.application.name=Vinilos
# ===============================
# CONFIGURACIÓN DE MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/vinilos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=Vinilos
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=8080
